@HomeCafeApi_HostAddress = https://localhost:7255

POST {{HomeCafeApi_HostAddress}}/menuitems
Content-Type: application/json

{
  "name": "Cappuccino",
  "description": "Rich espresso with steamed milk foam",
  "price": "4.50"
}

###

POST {{HomeCafeApi_HostAddress}}/orders
Content-Type: application/json

{
  "menuItemId": 4,
  "customerName": "Daisy",
  "sweetener": "Vanilla Syrup",
  "specialRequests": "Seriously?"
}

###

PATCH {{HomeCafeApi_HostAddress}}/orders/14
Content-Type: application/json

{
  "status": "Completed"
}

###
