// <auto-generated />
using System;
using HomeCafeApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeCafeApi.Migrations
{
    [DbContext(typeof(HomeCafeDb))]
    [Migration("20251214005628_ChangeOrderModel")]
    partial class ChangeOrderModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeCafeApi.Models.MenuItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("menu_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Rich espresso with steamed milk foam",
                            Name = "Cappuccino",
                            Price = 4.5m
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Smooth espresso with creamy milk",
                            Name = "Latte",
                            Price = 4.0m
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Chocolate espresso delight",
                            Name = "Mocha",
                            Price = 4.75m
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Spiced tea with steamed milk",
                            Name = "Chai Latte",
                            Price = 4.25m
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Creamy green tea latte",
                            Name = "Matcha Latte",
                            Price = 4.50m
                        });
                });

            modelBuilder.Entity("HomeCafeApi.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<long>("MenuItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("menu_item_id");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("text")
                        .HasColumnName("special_requests");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Sweetener")
                        .HasColumnType("text")
                        .HasColumnName("sweetener");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("HomeCafeApi.Models.Order", b =>
                {
                    b.HasOne("HomeCafeApi.Models.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
