// <auto-generated />
using System;
using HomeCafeApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeCafeApi.Migrations
{
    [DbContext(typeof(HomeCafeDb))]
    [Migration("20251221163549_UpdateMenuItemsSeedData")]
    partial class UpdateMenuItemsSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeCafeApi.Models.MenuItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("menu_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "espresso, steamed milk",
                            Name = "Cafe Latte"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "espresso, milk, ice",
                            Name = "Iced Cafe Latte"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "espresso, water, ice",
                            Name = "Iced Americano"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "espresso, hot water",
                            Name = "Americano"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "matcha, steamed milk",
                            Name = "Matcha Latte"
                        },
                        new
                        {
                            Id = 6L,
                            Description = "matcha, milk, ice",
                            Name = "Iced Matcha Latte"
                        },
                        new
                        {
                            Id = 7L,
                            Description = "hojicha, steamed milk",
                            Name = "Hojicha Latte"
                        },
                        new
                        {
                            Id = 8L,
                            Description = "hojicha, milk, ice",
                            Name = "Iced Hojicha Latte"
                        },
                        new
                        {
                            Id = 9L,
                            Description = "hot chocolate mix, steamed milk",
                            Name = "Hot Chocolate"
                        },
                        new
                        {
                            Id = 10L,
                            Description = "please ask JP for current tea selection",
                            Name = "Tea"
                        },
                        new
                        {
                            Id = 11L,
                            Description = "espresso, milk, ice, pumpkin syrup, whipped cream",
                            Name = "Iced Pumpkin Spice Latte (seasonal)"
                        },
                        new
                        {
                            Id = 12L,
                            Description = "espresso, milk, ice, chocolate sauce, peppermint flavor, whipped cream, candy cane topping",
                            Name = "Iced Peppermint Mocha (seasonal)"
                        },
                        new
                        {
                            Id = 13L,
                            Description = "jasmine tea, milk, ice",
                            Name = "Iced Jasmine Latte"
                        });
                });

            modelBuilder.Entity("HomeCafeApi.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<long>("MenuItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("menu_item_id");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("text")
                        .HasColumnName("special_requests");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Sweetener")
                        .HasColumnType("text")
                        .HasColumnName("sweetener");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("HomeCafeApi.Models.Order", b =>
                {
                    b.HasOne("HomeCafeApi.Models.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
